services:
  x-ui-bot:
    build: .
    container_name: x-ui-bot
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./config.yaml:/root/config.yaml:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
